"""initial schema

初始基线迁移：创建 db_client.py 定义的 17 张核心静态表。
对已存在的开发库（表已由 db_client 创建）使用 `alembic stamp head` 标记，不重复执行。
对全新库（如 PostgreSQL）则由 `alembic upgrade head` 建表。

Revision ID: 001_initial_schema
Revises:
Create Date: 2026-07-16 07:31:09.016689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_relationship_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=True),
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('old_properties', sa.Text(), nullable=True),
    sa.Column('new_properties', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_relationship_history', schema=None) as batch_op:
        batch_op.create_index('idx_graph_history_entity', ['source_entity_id', 'target_entity_id'], unique=False)
        batch_op.create_index('idx_graph_history_rel', ['relationship_id'], unique=False)

    op.create_table('memory_extraction_triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.Text(), nullable=False),
    sa.Column('query_snippet', sa.Text(), nullable=True),
    sa.Column('fragments_created', sa.Integer(), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_extraction_triggers', schema=None) as batch_op:
        batch_op.create_index('idx_extraction_user', ['user_id', 'created_at'], unique=False)

    op.create_table('memory_metrics_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('total_memories', sa.Integer(), nullable=True),
    sa.Column('active_memories', sa.Integer(), nullable=True),
    sa.Column('total_storage_bytes', sa.Integer(), nullable=True),
    sa.Column('daily_new_count', sa.Integer(), nullable=True),
    sa.Column('daily_recall_count', sa.Integer(), nullable=True),
    sa.Column('daily_recall_hit_count', sa.Integer(), nullable=True),
    sa.Column('avg_recall_latency_ms', sa.Float(), nullable=True),
    sa.Column('p50_recall_latency_ms', sa.Float(), nullable=True),
    sa.Column('p99_recall_latency_ms', sa.Float(), nullable=True),
    sa.Column('llm_extraction_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_rerank_tokens', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_metrics_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_snapshot_user', ['user_id', 'snapshot_time'], unique=False)

    op.create_table('memory_quality_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.Text(), nullable=False),
    sa.Column('evaluation_type', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evaluator', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_quality_evaluations', schema=None) as batch_op:
        batch_op.create_index('idx_quality_memory', ['user_id', 'memory_id'], unique=False)

    op.create_table('memory_trace_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Text(), nullable=True),
    sa.Column('memory_type', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_source', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_trace_events', schema=None) as batch_op:
        batch_op.create_index('idx_trace_memory', ['memory_id', 'event_type'], unique=False)
        batch_op.create_index('idx_trace_user', ['user_id', 'created_at'], unique=False)

    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.create_index('idx_perf_metrics_user_time', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_perf_metrics_user_type_time', ['user_id', 'metric_type', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('extraction_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Text(), nullable=False),
    sa.Column('rating', sa.Text(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_feedback', schema=None) as batch_op:
        batch_op.create_index('idx_extraction_feedback_user', ['user_id', 'created_at'], unique=False)

    op.create_table('extraction_prompt_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_extraction_templates_user_name')
    )
    with op.batch_alter_table('extraction_prompt_templates', schema=None) as batch_op:
        batch_op.create_index('idx_extraction_templates_user', ['user_id', 'is_active'], unique=False)

    op.create_table('graph_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', 'entity_type', name='uq_graph_entities')
    )
    with op.batch_alter_table('graph_entities', schema=None) as batch_op:
        batch_op.create_index('idx_graph_entities_name', ['user_id', 'name'], unique=False)
        batch_op.create_index('idx_graph_entities_user', ['user_id', 'entity_type'], unique=False)

    op.create_table('memory_delete_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.Text(), nullable=False),
    sa.Column('memory_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('old_content', sa.Text(), nullable=True),
    sa.Column('operator', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_fragments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fragment_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.Text(), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('lifecycle_status', sa.Text(), nullable=True),
    sa.Column('last_recalled_at', sa.DateTime(), nullable=True),
    sa.Column('cold_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_fragments', schema=None) as batch_op:
        batch_op.create_index('idx_memory_fragments_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_memory_fragments_user', ['user_id'], unique=False)

    op.create_table('memory_lifecycle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.Text(), nullable=False),
    sa.Column('memory_id', sa.Text(), nullable=False),
    sa.Column('lifecycle_status', sa.Text(), nullable=True),
    sa.Column('cold_reason', sa.Text(), nullable=True),
    sa.Column('cold_at', sa.DateTime(), nullable=True),
    sa.Column('last_recalled_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('soft_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('restore_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_lifecycle', schema=None) as batch_op:
        batch_op.create_index('idx_lifecycle_status', ['lifecycle_status'], unique=False)
        batch_op.create_index('idx_lifecycle_user_status', ['user_id', 'lifecycle_status'], unique=False)

    op.create_table('memory_merge_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.Text(), nullable=False),
    sa.Column('source_ids', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('merge_type', sa.Text(), nullable=False),
    sa.Column('merge_action', sa.Text(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_tables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('table_schema', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'table_name', name='uq_memory_tables_user_name')
    )
    with op.batch_alter_table('memory_tables', schema=None) as batch_op:
        batch_op.create_index('idx_memory_tables_user', ['user_id'], unique=False)

    op.create_table('memory_variables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_memory_variables_user_key')
    )
    with op.batch_alter_table('memory_variables', schema=None) as batch_op:
        batch_op.create_index('idx_memory_variables_user', ['user_id'], unique=False)

    op.create_table('graph_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('relation_subtype', sa.Text(), nullable=True),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('extraction_source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['source_entity_id'], ['graph_entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['graph_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_relationships', schema=None) as batch_op:
        batch_op.create_index('idx_graph_rels_active', ['user_id', 'relation_type', 'is_active'], unique=False)
        batch_op.create_index('idx_graph_rels_source', ['source_entity_id'], unique=False)
        batch_op.create_index('idx_graph_rels_target', ['target_entity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph_relationships', schema=None) as batch_op:
        batch_op.drop_index('idx_graph_rels_target')
        batch_op.drop_index('idx_graph_rels_source')
        batch_op.drop_index('idx_graph_rels_active')

    op.drop_table('graph_relationships')
    with op.batch_alter_table('memory_variables', schema=None) as batch_op:
        batch_op.drop_index('idx_memory_variables_user')

    op.drop_table('memory_variables')
    with op.batch_alter_table('memory_tables', schema=None) as batch_op:
        batch_op.drop_index('idx_memory_tables_user')

    op.drop_table('memory_tables')
    op.drop_table('memory_merge_log')
    with op.batch_alter_table('memory_lifecycle', schema=None) as batch_op:
        batch_op.drop_index('idx_lifecycle_user_status')
        batch_op.drop_index('idx_lifecycle_status')

    op.drop_table('memory_lifecycle')
    with op.batch_alter_table('memory_fragments', schema=None) as batch_op:
        batch_op.drop_index('idx_memory_fragments_user')
        batch_op.drop_index('idx_memory_fragments_expires')

    op.drop_table('memory_fragments')
    op.drop_table('memory_delete_log')
    with op.batch_alter_table('graph_entities', schema=None) as batch_op:
        batch_op.drop_index('idx_graph_entities_user')
        batch_op.drop_index('idx_graph_entities_name')

    op.drop_table('graph_entities')
    with op.batch_alter_table('extraction_prompt_templates', schema=None) as batch_op:
        batch_op.drop_index('idx_extraction_templates_user')

    op.drop_table('extraction_prompt_templates')
    with op.batch_alter_table('extraction_feedback', schema=None) as batch_op:
        batch_op.drop_index('idx_extraction_feedback_user')

    op.drop_table('extraction_feedback')
    op.drop_table('users')
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_index('idx_perf_metrics_user_type_time')
        batch_op.drop_index('idx_perf_metrics_user_time')

    op.drop_table('performance_metrics')
    with op.batch_alter_table('memory_trace_events', schema=None) as batch_op:
        batch_op.drop_index('idx_trace_user')
        batch_op.drop_index('idx_trace_memory')

    op.drop_table('memory_trace_events')
    with op.batch_alter_table('memory_quality_evaluations', schema=None) as batch_op:
        batch_op.drop_index('idx_quality_memory')

    op.drop_table('memory_quality_evaluations')
    with op.batch_alter_table('memory_metrics_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_snapshot_user')

    op.drop_table('memory_metrics_snapshots')
    with op.batch_alter_table('memory_extraction_triggers', schema=None) as batch_op:
        batch_op.drop_index('idx_extraction_user')

    op.drop_table('memory_extraction_triggers')
    with op.batch_alter_table('graph_relationship_history', schema=None) as batch_op:
        batch_op.drop_index('idx_graph_history_rel')
        batch_op.drop_index('idx_graph_history_entity')

    op.drop_table('graph_relationship_history')
    # ### end Alembic commands ###
